services:
  mongo_db_cart:
    image: mongo:7.0.8
    container_name: mongo_db_cart
    volumes:
      - ~/mongo_db_cart:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  payment_api:
    build:
      context: .
      dockerfile: container/Dockerfile
    image: cart_api:latest
    container_name: cart_api
    ports:
      - "8003:8000"
    environment:
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_HOST: "mongo_db_cart"
      MONGODB_PASS: ${MONGODB_PASS}
    depends_on:
      - mongo_db_cart
